[package]
name = "odbc-napi"
version = "3.0.0-rustalpha.4"
edition = "2024"
rust-version = "1.90"
license = "MIT"
description = "unixodbc bindings for node"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3", default-features = false, features = ["napi8"] }
napi-derive = "3"
odbc-api = "29"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
