const EventEmitter = require('events');

const { Connection } = require('./Connection');

const odbc = require('node-gyp-build')(__dirname + '/..');

const REUSE_CONNECTIONS_DEFAULT = true;
const INITIAL_SIZE_DEFAULT = 10;
const INCREMENT_SIZE_DEFAULT = 10;
const MAX_SIZE_DEFAULT = Number.MAX_SAFE_INTEGER;
const INITIAL_STATEMENTS_DEFAULT = [];
const SHRINK_DEFAULT = true;
const CONNECTION_TIMEOUT_DEFAULT = 0;
const LOGIN_TIMEOUT_DEFAULT = 0;
const MAX_ACTIVELY_CONNECTING = 1;

// A queue for tracking the connections 
class ConnectionQueue
{
  static queuedConnections = [];
  static activelyConnectingCount = 0;
  static maxActivelyConnecting = MAX_ACTIVELY_CONNECTING;

  static enqueue = async function(pool, promiseGenerator, configObject)
  {
      ConnectionQueue.queuedConnections.push({
          pool,
          promiseGenerator,
          configObject
      });
      ConnectionQueue.dequeue();
      return;
  }

  static dequeue = async function()
  {
    if (this.activelyConnectingCount >= this.maxActivelyConnecting) {
      return;
    }
    const item = this.queuedConnections.shift();
    if (!item) {
      return;
    }
    ConnectionQueue.activelyConnectingCount++;
    try {
      await item.promiseGenerator(item.configObject);
    } catch (error) {
      // Errors are handled in the promiseGenerator through emitting a
      // "connectionError" event. Error thrown and caught here simply to resolve
      // the promise generated by the promiseGenerator.
    }
    ConnectionQueue.activelyConnectingCount--;
    ConnectionQueue.dequeue();
    return;
  }
}

function parseInitialStatements(initialStatements) {
  if (initialStatements === undefined) return INITIAL_STATEMENTS_DEFAULT;

  if (!Array.isArray(initialStatements) || initialStatements.some((sql) => typeof sql !== 'string')) {
    throw new TypeError('Pool configuration option "initialStatements" must be an array of strings');
  }

  return initialStatements;
}

class Pool {

  constructor(connectionString) {

    this.connectionConfig = {};
    this.waitingConnectionWork = [];
    this.isOpen = false;
    this.freeConnections = [];
    this.connectionsBeingCreatedCount = 0;
    this.poolSize = 0;

    // Keeps track of when connections have sucessfully connected
    this.connectionEmitter = new EventEmitter();

    // Fires when a connection has been made. If a connect() call is waiting for
    // one, it gets this; otherwise the connection joins the free list.
    this.connectionEmitter.on('connected', (connection) => {
      const waiting = this.waitingConnectionWork.shift();
      if (waiting === undefined) {
        this.freeConnections.push(connection);
        return;
      }
      waiting.resolveFunction(connection);
    });

    // Fires when a connection failed. With nothing waiting the pool simply
    // stays empty, and the next caller is the one told about it.
    this.connectionEmitter.on('connectionError', (error) => {
      const waiting = this.waitingConnectionWork.shift();
      if (waiting === undefined) return;

      waiting.rejectFunction(error);
    });

    // connectionString is a string, so use defaults for all of the
    // configuration options.
    if (typeof connectionString === 'string') {
      this.connectionConfig.connectionString = connectionString;

      this.reuseConnections = REUSE_CONNECTIONS_DEFAULT;
      this.initialSize = INITIAL_SIZE_DEFAULT;
      this.incrementSize = INCREMENT_SIZE_DEFAULT;
      this.maxSize = MAX_SIZE_DEFAULT;
      this.shrink = SHRINK_DEFAULT;
      this.connectionConfig.connectionTimeout = CONNECTION_TIMEOUT_DEFAULT;
      this.connectionConfig.loginTimeout = LOGIN_TIMEOUT_DEFAULT;
      this.initialStatements = INITIAL_STATEMENTS_DEFAULT;
    }
    // connectionString is an object, so ensure that connectionString is a
    // property on that object and then copy over any configuration options.
    else if (typeof connectionString === 'object')
    {
      const configObject = connectionString;
      if (!Object.prototype.hasOwnProperty.call(configObject, 'connectionString')) {
        throw new TypeError('Pool configuration object must contain "connectionString" key');
      }

      this.connectionConfig.connectionString = configObject.connectionString;

      // reuseConnections
      this.reuseConnections = configObject.reuseConnections !== undefined ? configObject.reuseConnections : REUSE_CONNECTIONS_DEFAULT;

      // initialSize
      this.initialSize = configObject.initialSize !== undefined ? configObject.initialSize : INITIAL_SIZE_DEFAULT;

      // incrementSize
      this.incrementSize = configObject.incrementSize !== undefined ? configObject.incrementSize : INCREMENT_SIZE_DEFAULT;

      // maxSize
      this.maxSize = configObject.maxSize !== undefined ? configObject.maxSize : MAX_SIZE_DEFAULT;

      // shrink
      this.shrink = configObject.shrink !== undefined ? configObject.shrink : SHRINK_DEFAULT;

      // connectionTimeout
      this.connectionConfig.connectionTimeout = configObject.connectionTimeout !== undefined ? configObject.connectionTimeout : CONNECTION_TIMEOUT_DEFAULT;

      // loginTimeout
      this.connectionConfig.loginTimeout = configObject.loginTimeout !== undefined ? configObject.loginTimeout : LOGIN_TIMEOUT_DEFAULT;

      // initialStatements
      this.initialStatements = parseInitialStatements(configObject.initialStatements);
      

      // connectingQueueMax
      // unlike other configuration values, this one is set statically on the
      // ConnectionQueue object and not on the Pool intance
      if (configObject.maxActivelyConnecting !== undefined)
      {
        ConnectionQueue.maxActivelyConnecting = configObject.maxActivelyConnecting
      }
    }
    // connectionString was neither a string nor and object, so throw an error.
    else
    {
      throw TypeError('Pool constructor must passed a connection string or a configuration object');
    }
  }

  // returns a open connection, ready to use.
  // should overwrite the 'close' function of the connection, and rename it is 'nativeClose', so
  // that that close can still be called.
  /**
   * A connection from the pool, ready to use. Its `close` returns it to the
   * pool rather than closing it; `nativeClose` still closes it for real.
   * @returns {Promise<Connection>}
   */
  async connect() {
    if (this.freeConnections.length > 0) {
      return this.freeConnections.pop();
    }

    if (this.connectionsBeingCreatedCount <= this.waitingConnectionWork.length &&
        this.poolSize + this.connectionsBeingCreatedCount + this.incrementSize <= this.maxSize)
    {
      this.increasePoolSize(this.incrementSize);
    }

    return new Promise((resolve, reject) => {
      this.waitingConnectionWork.push({ resolveFunction: resolve, rejectFunction: reject });
    });
  }

  /**
   * Runs a query on a pooled connection and returns it to the pool afterwards.
   * @returns {Promise<Array>}
   */
  async query(sql, parameters = undefined) {
    const connection = await this.connect();
    try {
      return await connection.query(sql, parameters);
    } finally {
      await connection.close();
    }
  }

  /** Closes every connection the pool holds. */
  async close() {
    const connections = [...this.freeConnections];
    this.freeConnections.length = 0;
    this.isOpen = false;

    await Promise.all(connections.map((connection) => this.closeOne(connection)));
  }

  async closeOne(connection) {
    await connection.nativeClose();
    this.poolSize--;
  }

  /**
   * Fills the pool to its initial size, and takes one connection to prove the
   * connection string works before anyone relies on it.
   */
  async init() {
    if (this.isOpen) return;
    this.isOpen = true;

    await this.increasePoolSize(this.initialSize);
    this.freeConnections.unshift(await this.connect());
  }

  /**
   * Opens one connection for the pool.
   *
   * A connection error is emitted rather than thrown: with no work waiting there
   * is nobody to throw at, and an uncaught rejection would take the application
   * down. Whoever asks for a connection next receives it instead.
   */
  generateConnectPromise = async function(connectionConfig) {
    let nativeConnection;
    try {
      nativeConnection = await odbc.connect(connectionConfig);
    } catch (error) {
      this.pool.connectionsBeingCreatedCount--;
      this.pool.connectionEmitter.emit('connectionError', error);
      return;
    }

    this.pool.connectionsBeingCreatedCount--;
    this.pool.poolSize++;

    const connection = new Connection(nativeConnection);
    connection.nativeClose = connection.close.bind(connection);
    connection.close = this.pool.reuseConnections
      ? async () => this.pool.connectionEmitter.emit('connected', connection)
      : async () => {
          this.pool.increasePoolSize(1);
          await connection.nativeClose();
          this.pool.poolSize--;
        };

    try {
      await this.pool.runInitialStatements(connection);
    } catch (error) {
      this.pool.poolSize--;
      await connection.nativeClose().catch(() => {});
      this.pool.connectionEmitter.emit('connectionError', error);
      return;
    }

    this.pool.connectionEmitter.emit('connected', connection);
  }

  /**
   * Prepares a newly opened session before any work is handed to it.
   *
   * Ingres rejects `SET SESSION ISOLATION LEVEL` and `SET LOCKMODE` once a transaction is
   * active, so these run here, on each new session, rather than per checkout.
   */
  async runInitialStatements(connection) {
    for (const sql of this.initialStatements) {
      await connection.query(sql);
    }
  }

  // odbc.connect runs on an AsyncWorker, so this is truly non-blocking
  async increasePoolSize(count) {
    this.connectionsBeingCreatedCount += count;
    for (let i = 0; i < count; i++)
    {
      ConnectionQueue.enqueue(this, this.generateConnectPromise, this.connectionConfig);
    }
  }
}

module.exports.Pool = Pool;
