import { SQL_INTEGER, SQL_SMALLINT, SQL_VARCHAR } from "../../../lib/index.ts";
import type { ColumnDefinition } from "../../../lib/index.ts";

export const sqlColumnsColumns: readonly ColumnDefinition[] = [
  {
    name: "TABLE_CAT",
    dataType: SQL_VARCHAR,
    dataTypeName: "SQL_VARCHAR",
    columnSize: 128,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "TABLE_SCHEM",
    dataType: SQL_VARCHAR,
    dataTypeName: "SQL_VARCHAR",
    columnSize: 128,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "TABLE_NAME",
    dataType: SQL_VARCHAR,
    dataTypeName: "SQL_VARCHAR",
    columnSize: 128,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "COLUMN_NAME",
    dataType: SQL_VARCHAR,
    dataTypeName: "SQL_VARCHAR",
    columnSize: 128,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "DATA_TYPE",
    dataType: SQL_SMALLINT,
    dataTypeName: "SQL_SMALLINT",
    columnSize: 5,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "TYPE_NAME",
    dataType: SQL_VARCHAR,
    dataTypeName: "SQL_VARCHAR",
    columnSize: 128,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "COLUMN_SIZE",
    dataType: SQL_INTEGER,
    dataTypeName: "SQL_INTEGER",
    columnSize: 10,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "BUFFER_LENGTH",
    dataType: SQL_INTEGER,
    dataTypeName: "SQL_INTEGER",
    columnSize: 10,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "DECIMAL_DIGITS",
    dataType: SQL_SMALLINT,
    dataTypeName: "SQL_SMALLINT",
    columnSize: 5,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "NUM_PREC_RADIX",
    dataType: SQL_SMALLINT,
    dataTypeName: "SQL_SMALLINT",
    columnSize: 5,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "NULLABLE",
    dataType: SQL_SMALLINT,
    dataTypeName: "SQL_SMALLINT",
    columnSize: 5,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "REMARKS",
    dataType: SQL_VARCHAR,
    dataTypeName: "SQL_VARCHAR",
    columnSize: 254,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "COLUMN_DEF",
    dataType: SQL_VARCHAR,
    dataTypeName: "SQL_VARCHAR",
    columnSize: 254,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "SQL_DATA_TYPE",
    dataType: SQL_SMALLINT,
    dataTypeName: "SQL_SMALLINT",
    columnSize: 5,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "SQL_DATETIME_SUB",
    dataType: SQL_SMALLINT,
    dataTypeName: "SQL_SMALLINT",
    columnSize: 5,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "CHAR_OCTET_LENGTH",
    dataType: SQL_INTEGER,
    dataTypeName: "SQL_INTEGER",
    columnSize: 10,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "ORDINAL_POSITION",
    dataType: SQL_INTEGER,
    dataTypeName: "SQL_INTEGER",
    columnSize: 10,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "IS_NULLABLE",
    dataType: SQL_VARCHAR,
    dataTypeName: "SQL_VARCHAR",
    columnSize: 254,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "DISPLAY_SIZE",
    dataType: SQL_INTEGER,
    dataTypeName: "SQL_INTEGER",
    columnSize: 10,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "FIELD_TYPE",
    dataType: SQL_INTEGER,
    dataTypeName: "SQL_INTEGER",
    columnSize: 10,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "AUTO_INCREMENT",
    dataType: SQL_INTEGER,
    dataTypeName: "SQL_INTEGER",
    columnSize: 10,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "PHYSICAL NUMBER",
    dataType: SQL_SMALLINT,
    dataTypeName: "SQL_SMALLINT",
    columnSize: 5,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "TABLE OID",
    dataType: SQL_INTEGER,
    dataTypeName: "SQL_INTEGER",
    columnSize: 10,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "BASE TYPEID",
    dataType: SQL_INTEGER,
    dataTypeName: "SQL_INTEGER",
    columnSize: 10,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "TYPMOD",
    dataType: SQL_INTEGER,
    dataTypeName: "SQL_INTEGER",
    columnSize: 10,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "TABLE INFO",
    dataType: SQL_INTEGER,
    dataTypeName: "SQL_INTEGER",
    columnSize: 10,
    decimalDigits: 0,
    nullable: true,
  },
];

export const sqlTablesColumns: readonly ColumnDefinition[] = [
  {
    name: "TABLE_CAT",
    dataType: SQL_VARCHAR,
    dataTypeName: "SQL_VARCHAR",
    columnSize: 128,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "TABLE_SCHEM",
    dataType: SQL_VARCHAR,
    dataTypeName: "SQL_VARCHAR",
    columnSize: 128,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "TABLE_NAME",
    dataType: SQL_VARCHAR,
    dataTypeName: "SQL_VARCHAR",
    columnSize: 128,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "TABLE_TYPE",
    dataType: SQL_VARCHAR,
    dataTypeName: "SQL_VARCHAR",
    columnSize: 128,
    decimalDigits: 0,
    nullable: true,
  },
  {
    name: "REMARKS",
    dataType: SQL_VARCHAR,
    dataTypeName: "SQL_VARCHAR",
    columnSize: 254,
    decimalDigits: 0,
    nullable: true,
  },
];
