const odbc = require('../../../lib/odbc')

module.exports = {
  generateCreateOrReplaceQueries: function (tableName, fields) {
    const sqlQueries = []
    sqlQueries.push(`DROP TABLE IF EXISTS ${tableName}`)
    sqlQueries.push(`CREATE TABLE ${tableName} ${fields}`)
    return sqlQueries
  },
  sqlColumnsColumns: [
    {
      columnSize: 128,
      dataType: odbc.SQL_VARCHAR,
      dataTypeName: 'SQL_VARCHAR',
      decimalDigits: 0,
      name: 'TABLE_CAT',
      nullable: true,
    },
    {
      columnSize: 128,
      dataType: odbc.SQL_VARCHAR,
      dataTypeName: 'SQL_VARCHAR',
      decimalDigits: 0,
      name: 'TABLE_SCHEM',
      nullable: true,
    },
    {
      columnSize: 128,
      dataType: odbc.SQL_VARCHAR,
      dataTypeName: 'SQL_VARCHAR',
      decimalDigits: 0,
      name: 'TABLE_NAME',
      nullable: true,
    },
    {
      columnSize: 128,
      dataType: odbc.SQL_VARCHAR,
      dataTypeName: 'SQL_VARCHAR',
      decimalDigits: 0,
      name: 'COLUMN_NAME',
      nullable: true,
    },
    {
      columnSize: 5,
      dataType: odbc.SQL_SMALLINT,
      dataTypeName: 'SQL_SMALLINT',
      decimalDigits: 0,
      name: 'DATA_TYPE',
      nullable: true,
    },
    {
      columnSize: 128,
      dataType: odbc.SQL_VARCHAR,
      dataTypeName: 'SQL_VARCHAR',
      decimalDigits: 0,
      name: 'TYPE_NAME',
      nullable: true,
    },
    {
      columnSize: 10,
      dataType: odbc.SQL_INTEGER,
      dataTypeName: 'SQL_INTEGER',
      decimalDigits: 0,
      name: 'COLUMN_SIZE',
      nullable: true,
    },
    {
      columnSize: 10,
      dataType: odbc.SQL_INTEGER,
      dataTypeName: 'SQL_INTEGER',
      decimalDigits: 0,
      name: 'BUFFER_LENGTH',
      nullable: true,
    },
    {
      columnSize: 5,
      dataType: odbc.SQL_SMALLINT,
      dataTypeName: 'SQL_SMALLINT',
      decimalDigits: 0,
      name: 'DECIMAL_DIGITS',
      nullable: true,
    },
    {
      columnSize: 5,
      dataType: odbc.SQL_SMALLINT,
      dataTypeName: 'SQL_SMALLINT',
      decimalDigits: 0,
      name: 'NUM_PREC_RADIX',
      nullable: true,
    },
    {
      columnSize: 5,
      dataType: odbc.SQL_SMALLINT,
      dataTypeName: 'SQL_SMALLINT',
      decimalDigits: 0,
      name: 'NULLABLE',
      nullable: true,
    },
    {
      columnSize: 254,
      dataType: odbc.SQL_VARCHAR,
      dataTypeName: 'SQL_VARCHAR',
      decimalDigits: 0,
      name: 'REMARKS',
      nullable: true,
    },
    {
      columnSize: 254,
      dataType: odbc.SQL_VARCHAR,
      dataTypeName: 'SQL_VARCHAR',
      decimalDigits: 0,
      name: 'COLUMN_DEF',
      nullable: true,
    },
    {
      columnSize: 5,
      dataType: odbc.SQL_SMALLINT,
      dataTypeName: 'SQL_SMALLINT',
      decimalDigits: 0,
      name: 'SQL_DATA_TYPE',
      nullable: true,
    },
    {
      columnSize: 5,
      dataType: odbc.SQL_SMALLINT,
      dataTypeName: 'SQL_SMALLINT',
      decimalDigits: 0,
      name: 'SQL_DATETIME_SUB',
      nullable: true,
    },
    {
      columnSize: 10,
      dataType: odbc.SQL_INTEGER,
      dataTypeName: 'SQL_INTEGER',
      decimalDigits: 0,
      name: 'CHAR_OCTET_LENGTH',
      nullable: true,
    },
    {
      columnSize: 10,
      dataType: odbc.SQL_INTEGER,
      dataTypeName: 'SQL_INTEGER',
      decimalDigits: 0,
      name: 'ORDINAL_POSITION',
      nullable: true,
    },
    {
      columnSize: 254,
      dataType: odbc.SQL_VARCHAR,
      dataTypeName: 'SQL_VARCHAR',
      decimalDigits: 0,
      name: 'IS_NULLABLE',
      nullable: true,
    },
    {
      columnSize: 10,
      dataType: odbc.SQL_INTEGER,
      dataTypeName: 'SQL_INTEGER',
      decimalDigits: 0,
      name: 'DISPLAY_SIZE',
      nullable: true,
    },
    {
      columnSize: 10,
      dataType: odbc.SQL_INTEGER,
      dataTypeName: 'SQL_INTEGER',
      decimalDigits: 0,
      name: 'FIELD_TYPE',
      nullable: true,
    },
    {
      columnSize: 10,
      dataType: odbc.SQL_INTEGER,
      dataTypeName: 'SQL_INTEGER',
      decimalDigits: 0,
      name: 'AUTO_INCREMENT',
      nullable: true,
    },
    {
      columnSize: 5,
      dataType: odbc.SQL_SMALLINT,
      dataTypeName: 'SQL_SMALLINT',
      decimalDigits: 0,
      name: 'PHYSICAL NUMBER',
      nullable: true,
    },
    {
      columnSize: 10,
      dataType: odbc.SQL_INTEGER,
      dataTypeName: 'SQL_INTEGER',
      decimalDigits: 0,
      name: 'TABLE OID',
      nullable: true,
    },
    {
      columnSize: 10,
      dataType: odbc.SQL_INTEGER,
      dataTypeName: 'SQL_INTEGER',
      decimalDigits: 0,
      name: 'BASE TYPEID',
      nullable: true,
    },
    {
      columnSize: 10,
      dataType: odbc.SQL_INTEGER,
      dataTypeName: 'SQL_INTEGER',
      decimalDigits: 0,
      name: 'TYPMOD',
      nullable: true,
    },
    {
      columnSize: 10,
      dataType: odbc.SQL_INTEGER,
      dataTypeName: 'SQL_INTEGER',
      decimalDigits: 0,
      name: 'TABLE INFO',
      nullable: true,
    },
  ],
  sqlTablesColumns: [
    {
      columnSize: 128,
      dataType: odbc.SQL_VARCHAR,
      dataTypeName: 'SQL_VARCHAR',
      decimalDigits: 0,
      name: 'TABLE_CAT',
      nullable: true,
    },
    {
      columnSize: 128,
      dataType: odbc.SQL_VARCHAR,
      dataTypeName: 'SQL_VARCHAR',
      decimalDigits: 0,
      name: 'TABLE_SCHEM',
      nullable: true,
    },
    {
      columnSize: 128,
      dataType: odbc.SQL_VARCHAR,
      dataTypeName: 'SQL_VARCHAR',
      decimalDigits: 0,
      name: 'TABLE_NAME',
      nullable: true,
    },
    {
      columnSize: 128,
      dataType: odbc.SQL_VARCHAR,
      dataTypeName: 'SQL_VARCHAR',
      decimalDigits: 0,
      name: 'TABLE_TYPE',
      nullable: true,
    },
    {
      columnSize: 254,
      dataType: odbc.SQL_VARCHAR,
      dataTypeName: 'SQL_VARCHAR',
      decimalDigits: 0,
      name: 'REMARKS',
      nullable: true,
    },
  ],
}
