name: Build

on: pull_request

jobs:
  build-matrix:
    strategy:
      matrix:
        node-version:
          - 22.x
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies (macOS)
      if: ${{ startsWith(matrix.os, 'macos') }}
      run: brew install unixodbc
    - name: Install dependencies (Linux)
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: sudo apt-get update && sudo apt-get install -y unixodbc-dev
    - name: Build package
      run: npm ci --production --build-from-source
